---
- name: Ensure a path for vim addons exists.
  ansible.builtin.file:
    path: /var/lib/vim/addons/colors
    state: directory

- name: Copy the vim colorscheme
  ansible.builtin.copy:
    src: ir_black.vim
    dest: /var/lib/vim/addons/colors/

- name: Copy the global vim configuration
  ansible.builtin.copy:
    src: vimrc.local
    dest: /etc/
